name: fullstack2020-Project-Shcduled-health-check

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
jobs:
  healthCheck:
    runs-on: ubuntu-latest
    steps:
     - name: Heroku_deployment
       uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
       with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fullstack2020-project" #Must be unique in Heroku
          heroku_email: "delphi1004@hanmail.net"
          healthcheck: "https://fullstack2020-project.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
