name: fullstack2020-Project-Shcduled-health-check

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
jobs:
  healthCheck:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
          healthcheck: "https://fullstack2020-project.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
